import React from 'react'
import { hms, humanDate } from '../api.js'
import { SITE } from '../config/siteMeta.js'

/** The printable document behind "Save as PDF".
 *
 *  Deliberately rendered by the browser rather than generated server-side.
 *  A Python PDF library would need a bundled Unicode font plus Arabic glyph
 *  shaping and bidi reordering to get one Arabic line right; the browser
 *  already does all of that correctly, and Ctrl+P → Save as PDF is a first
 *  class feature of every OS. Zero dependencies, perfect scripts.
 */
export default function PrintView({ doc }) {
  if (!doc) return null

  const summary = doc.summary || {}
  const segments = doc.segments || []
  const translation = doc.translation || []
  const labels = doc.speaker_labels || {}
  const rtl = !!doc.is_rtl
  const name = (raw) => labels[raw] || raw || ''

  const block = (list, dir) => {
    const turns = []
    for (const seg of list) {
      const prev = turns[turns.length - 1]
      if (prev && prev.speaker === seg.speaker && seg.start - prev.end < 30) {
        prev.end = seg.end
        prev.text += ' ' + seg.text
      } else {
        turns.push({ speaker: seg.speaker, start: seg.start, end: seg.end, text: seg.text })
      }
    }
    return turns.map((t, i) => (
      <div className="p-turn" key={i}>
        <div className="p-turn-head">
          <span className="p-ts">{hms(t.start)}</span>
          {t.speaker && <span className="p-who">{name(t.speaker)}</span>}
        </div>
        <p dir={dir}>{t.text.trim()}</p>
      </div>
    ))
  }

  return (
    <div className="print-doc">
      <header className="p-head">
        <img src="/ss-mark.webp" alt="" />
        <div>
          <div className="p-brand">Stealth-Scribe</div>
          <div className="p-strap">{SITE.strapline}</div>
        </div>
      </header>

      <h1 className="p-title">{doc.title || doc.original_name}</h1>

      <table className="p-meta">
        <tbody>
          <tr><th>Recording</th><td>{doc.original_name}</td></tr>
          <tr><th>Recorded</th><td>{humanDate(doc.recorded_at)}</td></tr>
          <tr><th>Duration</th><td>{hms(doc.duration_sec)}</td></tr>
          <tr><th>Speakers</th><td>{Object.keys(labels).length || 1}</td></tr>
          <tr><th>Language</th><td>
            {doc.language_name || doc.language || 'unknown'}
            {translation.length > 0 && ' — translated to English'}
          </td></tr>
          <tr><th>Transcribed</th><td>{humanDate(doc.finished_at)}</td></tr>
          {doc.folder && <tr><th>Folder</th><td>{doc.folder}</td></tr>}
          {(doc.tags || []).length > 0 && (
            <tr><th>Tags</th><td>{doc.tags.join(', ')}</td></tr>
          )}
        </tbody>
      </table>

      {doc.notes && (
        <section className="p-section">
          <h2>Notes</h2>
          <p>{doc.notes}</p>
        </section>
      )}

      <section className="p-section">
        <h2>Summary</h2>
        <p>{summary.overview}</p>
        {(summary.key_points || []).length > 0 && (
          <>
            <h3>Key points</h3>
            <ul>{summary.key_points.map((k, i) => <li key={i}>{k}</li>)}</ul>
          </>
        )}
        {(summary.action_items || []).length > 0 && (
          <>
            <h3>Action items</h3>
            <ul>{summary.action_items.map((k, i) => <li key={i}>&#9744; {k}</li>)}</ul>
          </>
        )}
      </section>

      {translation.length > 0 ? (
        <>
          <section className="p-section p-break">
            <h2>Transcript — English translation</h2>
            <p className="p-note">
              Machine translation from {doc.language_name || doc.language}. Check
              anything that matters against the original.
            </p>
            {block(translation, 'ltr')}
          </section>
          <section className="p-section p-break">
            <h2>Transcript — original ({doc.language_name || doc.language})</h2>
            {block(segments, rtl ? 'rtl' : 'ltr')}
          </section>
        </>
      ) : (
        <section className="p-section p-break">
          <h2>Transcript</h2>
          {block(segments, rtl ? 'rtl' : 'ltr')}
        </section>
      )}

      <footer className="p-foot">
        Generated by Stealth-Scribe {SITE.url ? `· ${SITE.url.replace(/^https?:\/\//, '')}` : ''}
        {' · '}Automatic transcription may contain errors.
      </footer>
    </div>
  )
}
